jwt:
  secret: 'secret'
  issuer: AMR&Spring

server:
  port: 9090
database:
  file:
    repository: ./amr/data

logging:
  config: classpath:logback-spring.xml

amr:
  admin:
    id: admin
    pw: 1234
    name: 관리자

---
# LOCAL
spring:
  profiles:
    active: local

  redis:
    host: localhost
    port: 9010
    database: 0


---
#default 환경 / local
spring:
  profiles:
    - default
    - local