jwt:
  secret: 'secret'
  issuer: AMR&Spring

server:
  port: 9090
database:
  file:
    repository: ./amr/data

logging:
  config: classpath:logback-spring.xml

amr:
  admin:
    id: admin
    pw: 1234
    name: 관리자

---
# LOCAL
spring:
  profiles:
    active: local

  redis:
    host: localhost
    port: 9010
    database: 0

  datasource:
    url: jdbc:h2:mem:h2_jpa_sample;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

---
#default 환경 / local
spring:
  profiles:
    - default
    - local